### PR TITLE
Password Strength

### PR DESCRIPTION
**Pull request by awatson1978**

### CODE REVIEW

**Comment by awatson1978** [comment]
Hmmm....
Apparently `codetheweb:zxcvbn` uses Meteor 1.2 and `ecmascript`.  

``` bash
While selecting package versions:
   error: unknown package: isobuild:isopack-2
   Required by: codetheweb:zxcvbn 4.0.1

   unknown package: isobuild:compiler-plugin
   Required by: ecmascript 0.1.3-plugins.1
```

Had to take it out.

**Comment by awatson1978** [comment]
Okay, all the branches are merged, and we're getting the following errors.  Looks like your updates didn't have the latest from Erik because I was slow to merge them in.  

``` js
  ✓ ActiveEntry object should be loaded on client and server (84ms)
  ✓ Error messages should be empty by default 
  ✓ Email validation confirms it is a properly formatted email. 
  ✓ Password validation confirms it is a properly formatted password. 
  1) Password match confirms that two passwords are the same.
  ✓ Fullname validation confirms that at least a first and last name are entered. 
  2) Newly created user record should have role, profile, and name set.
  3) Newly created user should have fullName(), preferredName(), and familyName() methods.
  ✓ Newly created user can sign in to the application. 
  ✓ Newly created user can sign out of the application. 
```

**Comment by awatson1978** [comment]
Okay.... sorry for breaking things; but we had false positives before, because the `password-strength` branch was running on CircleCI with code checked out from the master branch.  I've updated the `circle.yml` file to use the current branch code.  Good news is that it's compiling and running correctly on CircleIC; bad news is that there are errors we need to fix.

Long story short...  please lets not _replace_ tests in the future by changing parameters.  New tests for strong passwords should be added _in addition_ to the existing tests.  

But no worries.  That's what feature branches are for.  Master is still passing green; and this is all part of the process.  Pull the branch to get the latest (broken) code that needs debugging.  

``` sh
git pull origin password-strength
```

Going to sleep on this and think the best way to get things back on track.  We'll probably want to basically reset the test scripts with the script from the `master` branch.  Add the new strong password tests.  Update things to pass the old tests and the new tests.

**Comment by awatson1978** [comment]
In particular, the `.signUp()` function isn't behaving as expected when we use the original test scripts.  

``` js
// broken
ActiveEntry.signUp('janedoe@test.org', 'Janedoe123', 'Janedoe123', 'Jane Doe');
```

We need to configure the ActiveEntry object during some of these test runs, like so:

``` js
  it('Newly created user record should have role, profile, and name set.', function () {
    ActiveEntry.configure({
      passwordOptions: {
        requireStrongPasswords: false
      }
    });
    // the rest of the test
  });
```

And then we can add a new test like so:

``` js
  it('Can require strong passwords to create a new user.', function () {
    ActiveEntry.configure({
      passwordOptions: {
        requireStrongPasswords: true
      }
    });
    // the rest of the test
  });

```

**Comment by awatson1978** [comment]
Do take a look at the Network Graph to follow along what happened as I merged in Erik's branch, made fixes, and moved the new code into the feature branch.  Ignore the validation-tests branch.  

https://github.com/clinical-meteor/active-entry/network

**Comment by awatson1978** [comment]
Got all the merge conflicts resolved, and tests passing green again.  Had to comment out some of the strong password checks, but the code is still in there, ready for another round and to be reenabled.

Do a `git pull origin develop`, create a new feature branch like last time, and let's repeat the process.  :)

I'd recommend keeping the PRs a bit smaller until we get into a flow.  The last one had maybe three or four different features in it (success messages, strong passwords, strength bar).

**Comment by ayselafsar** [comment]
I will try to make these changes asap.

**Comment by ayselafsar** [comment]
Hi Abigail, 
I am getting "Newly created user should have fullName(), preferredName(), and familyName() methods." error when I run activeEntryTests.js.  
We have the following code block in activeEntryTests.js: 

var user = Meteor.users.findOne({'emails.address': 'janedoe@test.org'});
expect(user.fullName()).to.equal('Jane Doe');
expect(user.givenName()).to.equal('Jane');
expect(user.familyName()).to.equal('Doe');

Actually, we do not have these methods for user object and fullName is a property of user.profile. Should we need to change the test case or am I missing something?
Thanks!

**Comment by awatson1978** [comment]
Ah, that functionality is provided by `clinical:user-model`.
https://github.com/clinical-meteor/user-model

You can simply run `meteor add clinical:user-model` to get the tests passing now.  Although a better solution is probably to log an issue in the `user-model` repository to reimplement, and then comment it out of the `active-entry` repository.  Mind copy/pasting it to https://github.com/clinical-meteor/user-model/issues?

**Comment by ayselafsar** [comment]
Yes, It works when I add clinical:user-model package.

**Pull request merged**
